// src/renderer/src/routes/youtube/toolbar.tsx
import { cn } from "@renderer/lib/utils";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowLeftIcon, MaximizeIcon, Minimize2, XIcon } from "lucide-react";
import { useMemo } from "react";
import { ToolbarOptions } from "@/components/toolbar-options";
import { Spinner } from "@/components/ui/spinner";
import { useNavigation } from "@/hooks/use-navigation";
import { useMainWindowState } from "@/hooks/use-settings";
import { useTrack } from "@/hooks/use-track";
import { useUpdater } from "@/hooks/use-updater";
import { useWindowControls } from "@/hooks/use-window-controls";

export const Route = createFileRoute("/youtube/toolbar")({
	component: YoutubeToolbarPage,
});

function YoutubeToolbarPage() {
	const appVersion = useMemo(() => window.api.version, []);
	const isDarwin = useMemo(() => window.app.platform === "darwin", []);
	const [state] = useMainWindowState();
	const track = useTrack();
	const { updateInfo, downloaded, progress, isPending: updatePending, runUpdate } = useUpdater();
	const { minimize, maximize, quit } = useWindowControls();
	const { goback } = useNavigation();

	const title = useMemo(() => track?.video?.title ?? null, [track]);
  const canGoBack = useMemo(() => state?.navigation?.canGoBack ?? false, [state?.navigation]);

	return (
		<div className="h-full overflow-hidden">
			<div className={`flex h-10 items-stretch justify-between gap-2 border-b border-gray-800 bg-black px-2 select-none ${isDarwin ? "pl-20" : ""}`}>
				<button
					type="button"
					className={cn("control-button self-center cursor-pointer", !canGoBack && "disabled")}
					disabled={!canGoBack}
					onClick={() => void goback()}
				>
					<ArrowLeftIcon />
				</button>
				<div className="drag flex flex-1 items-center gap-2">
					{!isDarwin && (
						<div className="flex items-center gap-1">
							<div className="-mt-px flex-none text-xs">YouTube Music for Desktop</div>
							{appVersion !== undefined && <div className="text-xs text-white opacity-30">v{appVersion}</div>}
						</div>
					)}
					{title && (
						<div className="flex h-7 items-center truncate rounded bg-blue-500/50 px-3 text-xs">
							<span className="truncate text-ellipsis">{title}</span>
						</div>
					)}
				</div>
				<div className="flex items-center gap-2">
					{isDarwin && appVersion && (
						<>
							<div className="text-xs text-white opacity-30">v{appVersion}</div>
							<div className="h-6 w-px bg-gray-600" />
						</>
					)}
					{updateInfo && (
						<button
							type="button"
							className={`flex h-7 cursor-pointer items-center gap-2 truncate rounded px-3 text-xs transition duration-100 ease-out ${
								updateInfo && !progress && !downloaded ? "bg-green-500 text-white" : downloaded ? "text-green-500" : ""
							}`}
							disabled={updatePending}
							onClick={() => void runUpdate()}
						>
							{progress?.percent ? (
								<>
									<Spinner size="sm" />
									<span>
										Downloading Update v{updateInfo.version}... {progress.percent.toFixed(0).padStart(5)}%
									</span>
								</>
							) : (
								<span className="truncate text-ellipsis">New Update v{updateInfo.version}</span>
							)}
						</button>
					)}
					<ToolbarOptions />
					{!isDarwin && (
						<>
							<div className="h-6 w-px bg-gray-600" />
							<div className="flex items-center gap-1">
								<button type="button" className="control-button" onClick={() => void minimize()}>
									<Minimize2 />
								</button>
								<button type="button" className="control-button" onClick={() => void maximize()}>
									<MaximizeIcon />
								</button>
								<button type="button" className="control-button control-button-danger" onClick={() => void quit()}>
									<XIcon />
								</button>
							</div>
						</>
					)}
				</div>
			</div>
		</div>
	);
}

// src/views/youtube/toolbar.vue
<template>
  <div class="h-full overflow-hidden">
    <div class="flex items-stretch justify-between border-b bg-black border-gray-600 select-none h-10 px-2 space-x-2">
      <div class="flex items-center flex-1 drag space-x-2 appear">
        <div class="flex items-center space-x-1">
          <div class="text-xs label -mt-px flex-none">YouTube Music for Desktop</div>
          <div class="text-xs opacity-30 text-white" v-if="appVersion !== undefined">v{{ appVersion }}</div>
        </div>
        <div class="text-xs bg-primary h-7 rounded items-center px-3 bg-opacity-50 appear flex truncate" v-if="title">
          <span class="truncate overflow-ellipsis">{{ title }}</span>
        </div>
      </div>
      <div class="flex items-center space-x-2">
        <template v-if="updateInfo">
          <button class="text-xs bg-green-500 h-7 rounded items-center px-3 transition duration-100 ease-out appear flex truncate cursor-pointer" :class="{ 'bg-green-500': updateInfo && !updateInfoProgress && !updateDownloaded, 'text-green-500' : updateDownloaded }" @click="() => runUpdate()">
            <template v-if="updateInfoProgress?.percent">Downloading Update v{{updateInfo.version}}... {{updateInfoProgress.percent.toFixed(0).padStart(5)}}%</template>
            <template v-else>
              <span class="truncate overflow-ellipsis">New Update v{{updateInfo.version}}</span>
            </template>
          </button>
        </template>
        <toolbar-options></toolbar-options>
        <div class="w-px h-6 bg-gray-600"></div>
        <div class="flex items-center space-x-1">
          <div @click="onMin" class="control-button">
            <MinIcon />
          </div>
          <div @click="onMax" class="control-button">
            <MaxIcon />
          </div>
          <div @click="onClose" class="control-button control-button-danger">
            <CloseIcon />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { defineComponent, ref } from "vue";
import CloseIcon from "@/assets/icons/close.svg";
import MaxIcon from "@/assets/icons/max-window.svg";
import MinIcon from "@/assets/icons/min-window.svg";
import ToolbarOptions from "./toolbar-options.vue";
import { refIpc } from "@/utils/Ipc";
const appVersion = ref(window.api.version);
export default defineComponent({
  components: {
    CloseIcon,
    MaxIcon,
    MinIcon,
    ToolbarOptions,
  },
  setup() {
    const [title] = refIpc("TRACK_TITLE_CHANGE", {
      ignoreUndefined: true,
      defaultValue: null,
    });
    const [updateInfo, setUpdateInfo] = refIpc("APP_UPDATE", {
      ignoreUndefined: true,
      defaultValue: null,
    });
    const [updateInfoProgress] = refIpc("APP_UPDATE_PROGRESS", {
      ignoreUndefined: true,
      defaultValue: null,
    });
    const [updateDownloaded] = refIpc("APP_UPDATE_DOWNLOADED", {
      ignoreUndefined: true,
      defaultValue: null,
      mapper: (x) => !!x,
    });
    const isInstalling = ref(false);
    return {
      title,
      appVersion,
      updateInfo,
      updateInfoProgress,
      updateDownloaded,
      runUpdate() {
        if (isInstalling.value) return;
        isInstalling.value = true;
        return window.api
          .action("app.installUpdate")
          .then(() => {
            setUpdateInfo(null);
          })
          .finally(() => {
            isInstalling.value = false;
          });
      },
    };
  },
  beforeRouteLeave() {
    return;
  },
  methods: {
    onClose() {
      window.api.quit();
    },
    onMax() {
      window.api.maximize();
    },
    onMin() {
      window.api.minimize();
    },
  },
  created() {},
});
</script>

<style lang="scss">
html,
body {
  @apply overflow-hidden;
}
</style>
