// src/renderer/src/components/SettingsInput.vue
<template>
  <div :class="['form-control', $attrs.class]">
    <label class="label">
      <span class="label-text text-gray-300">
        <slot name="label"></slot>
      </span>
    </label>
    <template v-if="$attrs.type === 'file'">
      <div class="flex space-x-2 items-center">
        <div class="text-gray-300 flex-1 bg-white bg-opacity-5 text-sm h-12 rounded-lg flex items-center px-3"> {{ value }} </div>
        <button class="btn btn-primary"
                @click="() => fileInputRef && fileInputRef.click()"> Browse </button>
      </div>
      <input ref="fileInputRef"
             :type="$attrs.type"
             :placeholder="$attrs.placeholder as string"
             :accept="$attrs.accept as string"
             class="hidden"
             @change="(ev) => updateSetting(ev.target as any)" />
    </template>
    <input v-else
           :type="$attrs.type as string"
           :placeholder="$attrs.placeholder as string"
           :value="value"
           class="input input-ghost"
           @change="(ev) => updateSetting(ev.target as any)" />
    <slot name="hint"></slot>
  </div>
</template>
<script lang="ts">
import { clamp, debounce } from "lodash-es";
import { defineComponent, onBeforeMount, ref } from "vue";

export default defineComponent({
	props: {
		configKey: {
			type: String,
			required: true,
		},
		defaultValue: Object,
		min: Number,
		max: Number,
	},
	setup(context) {
		const value = ref<any>(),
			fileInputRef = ref<any>();
		onBeforeMount(async () => {
			const res = await (window as any).api.settingsProvider.get(context.configKey, context.defaultValue ?? null);
			value.value = res;
			console.log({ value: value.value });
		});
		const updateSetting = ref<(_ev: HTMLInputElement) => null>(
			debounce((ev: HTMLInputElement) => {
				if (context.configKey) {
					if (ev.type === "file" && ev.files.length === 0) return;
					let inputValue: any;
					if ((ev.type === "number" && context.min !== undefined) || context.max !== undefined) {
						const minValue = context.min ?? ev.valueAsNumber;
						const maxValue = context.max ?? ev.valueAsNumber;
						inputValue = clamp(Number(ev.value), minValue, maxValue);
					} else {
						inputValue = ev.type === "file" ? window.api.getPathFromFile(ev.files[0]) : ev.value;
					}
					(window as any).api.settingsProvider.update(context.configKey, inputValue).then((v) => (value.value = inputValue = v));
				}
			}, 500) as any,
		);
		return {
			value,
			fileInputRef,
			updateSetting,
		};
	},
});
</script>
<style></style>

// src/renderer/src/components/settings-input.tsx
import { clamp, debounce } from "lodash-es";
import { type InputHTMLAttributes, type ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useSetting } from "@/hooks/use-settings";
import { cn } from "@/lib/utils";

export interface SettingsInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "onChange" | "value" | "defaultValue"> {
	configKey: string;
	defaultValue?: unknown;
	min?: number;
	max?: number;
	label?: ReactNode;
	hint?: ReactNode;
	className?: string;
}

export function SettingsInput({ configKey, defaultValue, min, max, label, hint, className, type = "text", ...attrs }: SettingsInputProps) {
	const [storedValue, setStoredValue] = useSetting(configKey, defaultValue ?? "");
	const [value, setValue] = useState<any>(storedValue ?? defaultValue ?? "");
	const fileInputRef = useRef<HTMLInputElement>(null);

	useEffect(() => {
		setValue(storedValue ?? defaultValue ?? "");
	}, [storedValue, defaultValue]);

	const updateSetting = useMemo(
		() =>
			debounce((ev: HTMLInputElement) => {
				if (ev.type === "file" && (!ev.files || ev.files.length === 0)) return;
				let inputValue: unknown;
				if (ev.type === "number" && (min !== undefined || max !== undefined)) {
					const minValue = min ?? ev.valueAsNumber;
					const maxValue = max ?? ev.valueAsNumber;
					inputValue = clamp(Number(ev.value), minValue, maxValue);
				} else {
					inputValue = ev.type === "file" ? window.api.getPathFromFile(ev.files![0]) : ev.value;
				}
				setStoredValue(inputValue as typeof storedValue);
			}, 500),
		[setStoredValue, min, max],
	);

	if (type === "file") {
		return (
			<div className={cn("flex flex-col gap-2", className)}>
				{label && <Label>{label}</Label>}
				<div className="flex items-center gap-2">
					<div className="flex h-12 flex-1 items-center rounded-lg bg-white/5 px-3 text-sm text-muted-foreground">{value}</div>
					<Button type="button" onClick={() => fileInputRef.current?.click()}>
						Browse
					</Button>
				</div>
				<input
					ref={fileInputRef}
					type="file"
					className="hidden"
					accept={attrs.accept}
					onChange={(ev) => updateSetting(ev.target)}
				/>
				{hint}
			</div>
		);
	}

	return (
		<div className={cn("flex flex-col gap-2", className)}>
			{label && <Label>{label}</Label>}
			<Input
				type={type}
				placeholder={attrs.placeholder}
				value={value ?? ""}
				min={min}
				max={max}
				onChange={(ev) => updateSetting(ev.target)}
			/>
			{hint}
		</div>
	);
}
