// src/renderer/src/routes/taskview.tsx
import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import ExitIcon from "@/assets/icons/close.svg?react";
import SettingsIcon from "@/assets/icons/settings.svg?react";
import { trpc } from "@/lib/trpc";

export const Route = createFileRoute("/taskview")({
	component: TaskViewPage,
});

function TaskViewPage() {
	const [showWinBorder, setShowWinBorder] = useState(false);
	const accentColor = "#a0a0a0";
	const { data: isWin11 } = trpc.app.isWin11.useQuery();

	useEffect(() => {
		document.title = "YouTube Music - Task View";
	}, []);

	useEffect(() => {
		if (isWin11 === undefined) return;
		setShowWinBorder(window.process.platform === "win32" ? !isWin11 : false);
	}, [isWin11]);

	return (
		<div
			className="absolute inset-0 flex h-full flex-col overflow-hidden bg-black"
			style={accentColor && showWinBorder ? { border: `1px solid ${accentColor}` } : undefined}
		>
			<div className="flex h-10 items-stretch justify-between border-b border-gray-600 bg-black px-2 select-none">
				<div className="flex flex-auto items-center px-2">
					<div className="text-sm">{window.translations?.appName ?? "YouTube Music"}</div>
				</div>
				<div className="flex flex-shrink-0 items-center gap-2">
					<div className="h-6 w-px bg-gray-600" />
					<button type="button" className="control-button" onClick={() => window.api.openWindow("settingsWindow")}>
						<SettingsIcon />
					</button>
				</div>
			</div>
			<div className="overflow-x-hidden overflow-y-auto">
				<div className="mx-2 mt-2 mb-6 flex flex-col gap-2">
					<button type="button" className="task-menu-item">
						Test
					</button>
					<button type="button" className="task-menu-item">
						Test
					</button>
					<button type="button" className="task-menu-item">
						Test
					</button>
					<button type="button" className="task-menu-item flex items-center gap-2" onClick={() => window.api.quit(true)}>
						<ExitIcon className="size-4" />
						<span>Exit App</span>
					</button>
				</div>
			</div>
			<style>{`
.task-menu-item {
  min-height: 40px;
  padding: 0 12px;
  cursor: pointer;
  background: rgb(24 24 27 / 0.6);
  border-radius: 4px;
  font-size: 14px;
  font-weight: 600;
  text-align: left;
  transition: transform 0.15s;
  user-select: none;
}
.task-menu-item:hover, .task-menu-item:active { background: rgb(24 24 27 / 0.8); }
.task-menu-item:active { transform: scale(0.98); }
`}</style>
		</div>
	);
}

// src/renderer/src/views/task-view/index.vue
<template>
  <div class="h-full absolute inset-0 overflow-hidden bg-black flex flex-col"
       :style="{
        ...(accentColor && showWinBorder ? { border: `1px solid ${accentColor}` } : {}),
      }">
    <div class="flex items-stretch justify-between border-b bg-black border-gray-600 select-none h-10 px-2">
      <div class="flex-auto flex items-center px-2">
        <div class="text-sm">{{ translations.appName }}</div>
      </div>
      <div class="flex items-center space-x-2 flex-shrink-0">
        <slot name="divider">
          <div class="w-px h-6 bg-gray-600"></div>
        </slot>
        <div class="flex items-center space-x-1">
          <div class="control-button"
               @click="() => window.api.openWindow('settingsWindow')">
            <SettingsIcon />
          </div>
        </div>
      </div>
    </div>
    <div class="overflow-y-auto overflow-x-hidden">
      <div class="task-menu">
        <button class="task-menu-item">Test</button>
        <button class="task-menu-item">Test</button>
        <button class="task-menu-item">Test</button>
        <button class="task-menu-item"
                @click="() => api.quit(true)">
          <ExitIcon class="w-4 h-4" />
          <span>Exit App</span>
        </button>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { TrackData } from "@main/utils/trackData";
import ExitIcon from "@renderer/assets/icons/close.svg";
import SettingsIcon from "@renderer/assets/icons/settings.svg";
import { refIpc } from "@shared/utils/Ipc";
import { ref } from "vue";

const showWinBorder = ref(false);
const accentColor = ref<string | null>("#a0a0a0"); // todo

const [, setTrack] = refIpc<TrackData>("TRACK_CHANGE", {
	ignoreUndefined: true,
	defaultValue: null,
});
document.title = `YouTube Music - Task View`;
Promise.all([window.process.isWin11(), window.ipcRenderer.invoke("api/track")]).then(([isWin11, currentTrack]) => {
	showWinBorder.value = window.process.platform === "win32" ? !isWin11 : false;
	setTrack(currentTrack);
});
</script>
<style lang="scss">
.task-menu {
  @apply mt-2 mb-6 mx-2 flex flex-col space-y-2;

  &-item {
    @apply min-h-[40px] px-3 cursor-pointer bg-zinc-900/60 rounded text-sm font-semibold text-left transition-transform select-none flex items-center space-x-2;

    &:hover,
    &:active {
      @apply bg-zinc-900/80;
    }

    &:active {
      @apply scale-[.98];
    }
  }
}
</style>
