// src/components/SectionCard.vue
<template>
  <div class="bg-opacity-5 bg-white shadow sm:rounded-lg mt-4 relative overflow-hidden">
    <div
      class="absolute inset-0 bg-gray-600/70 flex items-center justify-center text-gray-200 text-sm"
      v-if="loading === true"
    >
      <progress class="progress progress-primary bg-transparent w-24"></progress>
    </div>
    <div class="px-4 py-5 sm:p-6">
      <slot></slot>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { defineProps } from "vue";
const props = defineProps({
  loading: Boolean,
});
</script>

<style></style>

// apps/ytmdesktop2/src/renderer/src/components/section-card.tsx
import type { ReactNode } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Spinner } from "@/components/ui/spinner";
import { cn } from "@/lib/utils";

export interface SectionCardProps {
	loading?: boolean;
	className?: string;
	children?: ReactNode;
	onClick?: () => void;
}

export function SectionCard({ loading, className, children, onClick }: SectionCardProps) {
	return (
		<Card
			className={cn("relative cursor-default overflow-hidden transition-colors", onClick && "cursor-pointer hover:bg-accent/40", className)}
			onClick={onClick}
		>
			{loading && (
				<div className="absolute inset-0 z-10 flex items-center justify-center bg-background/70">
					<Spinner />
				</div>
			)}
			<CardContent>{children}</CardContent>
		</Card>
	);
}
