// src/renderer/src/components/SettingsInput.vue
<template>
  <div :class="['form-control', $attrs.class]">
    <label class="label">
      <span class="label-text text-gray-300">
        <slot name="label"></slot>
      </span>
    </label>
    <template v-if="$attrs.type === 'file'">
      <div class="flex space-x-2 items-center">
        <div class="text-gray-300 flex-1 bg-white bg-opacity-5 text-sm h-12 rounded-lg flex items-center px-3"> {{ value }} </div>
        <button class="btn btn-primary"
                @click="() => fileInputRef && fileInputRef.click()"> Browse </button>
      </div>
      <input ref="fileInputRef"
             :type="$attrs.type"
             :placeholder="$attrs.placeholder as string"
             :accept="$attrs.accept as string"
             class="hidden"
             @change="(ev) => updateSetting(ev.target as any)" />
    </template>
    <input v-else
           :type="$attrs.type as string"
           :placeholder="$attrs.placeholder as string"
           :value="value"
           class="input input-ghost"
           @change="(ev) => updateSetting(ev.target as any)" />
    <slot name="hint"></slot>
  </div>
</template>
<script lang="ts">
import { clamp, debounce } from "lodash-es";
import { defineComponent, onBeforeMount, ref } from "vue";

export default defineComponent({
	props: {
		configKey: {
			type: String,
			required: true,
		},
		defaultValue: Object,
		min: Number,
		max: Number,
	},
	setup(context) {
		const value = ref<any>(),
			fileInputRef = ref<any>();
		onBeforeMount(async () => {
			const res = await (window as any).api.settingsProvider.get(context.configKey, context.defaultValue ?? null);
			value.value = res;
			console.log({ value: value.value });
		});
		const updateSetting = ref<(_ev: HTMLInputElement) => null>(
			debounce((ev: HTMLInputElement) => {
				if (context.configKey) {
					if (ev.type === "file" && ev.files.length === 0) return;
					let inputValue: any;
					if ((ev.type === "number" && context.min !== undefined) || context.max !== undefined) {
						const minValue = context.min ?? ev.valueAsNumber;
						const maxValue = context.max ?? ev.valueAsNumber;
						inputValue = clamp(Number(ev.value), minValue, maxValue);
					} else {
						inputValue = ev.type === "file" ? window.api.getPathFromFile(ev.files[0]) : ev.value;
					}
					(window as any).api.settingsProvider.update(context.configKey, inputValue).then((v) => (value.value = inputValue = v));
				}
			}, 500) as any,
		);
		return {
			value,
			fileInputRef,
			updateSetting,
		};
	},
});
</script>
<style></style>

// apps/ytmdesktop2/src/renderer/src/components/settings-input.tsx
import { clamp } from "lodash-es";
import { type InputHTMLAttributes, type ReactNode, useId, useRef } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Field, FieldContent, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { useSettingsState } from "@/hooks/use-settings";
import { cn } from "@/lib/utils";

const DEFAULT_INPUT_DEBOUNCE_MS = 800;

export interface SettingsInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "onChange" | "value" | "defaultValue"> {
	configKey: string;
	defaultValue?: unknown;
	min?: number;
	max?: number;
	label?: ReactNode;
	hint?: ReactNode;
	className?: string;
	/** Persist debounce in ms (default 800). Keeps field editable while typing. */
	debounce?: number;
	/** Shown via sonner after the value is saved. */
	updateMessage?: string;
}

export function SettingsInput({
	configKey,
	defaultValue = "",
	min,
	max,
	label,
	hint,
	className,
	type = "text",
	debounce = DEFAULT_INPUT_DEBOUNCE_MS,
	updateMessage,
	...attrs
}: SettingsInputProps) {
	const id = useId();
	const [value, setValue, { isPending }] = useSettingsState(configKey, defaultValue, {
		debounce,
		onPersisted: updateMessage ? () => toast.success(updateMessage) : undefined,
	});
	const fileInputRef = useRef<HTMLInputElement>(null);

	if (type === "file") {
		return (
			<Field data-disabled={isPending || undefined} className={cn(className)}>
				{label ? <FieldLabel htmlFor={id}>{label}</FieldLabel> : null}
				<FieldContent>
					<div className="flex items-center gap-2">
						<div className="flex h-8 min-w-0 flex-1 items-center truncate rounded-lg border border-input bg-transparent px-2.5 text-xs text-muted-foreground">
							{String(value || "No file selected")}
						</div>
						<Button type="button" variant="outline" size="sm" disabled={isPending} onClick={() => fileInputRef.current?.click()}>
							Browse
						</Button>
					</div>
					<input
						ref={fileInputRef}
						id={id}
						type="file"
						className="hidden"
						accept={attrs.accept}
						disabled={isPending}
						onChange={(ev) => {
							const file = ev.target.files?.[0];
							if (!file) return;
							setValue(window.api.getPathFromFile(file));
						}}
					/>
					{hint}
				</FieldContent>
			</Field>
		);
	}

	return (
		<Field data-disabled={isPending || undefined} className={cn(className)}>
			{label ? <FieldLabel htmlFor={id}>{label}</FieldLabel> : null}
			<Input
				{...attrs}
				id={id}
				type={type}
				value={String(value ?? "")}
				min={min}
				max={max}
				disabled={isPending || attrs.disabled}
				onChange={(ev) => {
					if (type === "number" && (min !== undefined || max !== undefined)) {
						const n = Number(ev.target.value);
						if (!Number.isFinite(n)) {
							setValue(ev.target.value);
							return;
						}
						setValue(clamp(n, min ?? n, max ?? n));
						return;
					}
					setValue(ev.target.value);
				}}
			/>
			{hint ? <FieldDescription>{hint}</FieldDescription> : null}
		</Field>
	);
}
