// src/renderer/src/views/youtube/login-notice.vue
<template>
  <div class="flex flex-col h-full overflow-hidden">
    <ControlBar title="Google - Login" class="flex-shrink-0">
      <template #divider>&nbsp;</template>
    </ControlBar>
    <div
      class="bg-blue-500 text-white flex flex-auto items-center text-sm select-none pointer-events-none flex-shrink-0"
    >
      <div class="flex items-start justify-center space-x-2 container">
        <AlertIcon class="h-4 w-4 mt-1 flex-shrink-0"></AlertIcon>
        <div class="flex flex-col leading-tight">
          <p>
            If there are any issues logging in, press <strong>try again</strong> until it works.
          </p>
          <p class="break-words">
            This is happening due to google tightening security on unofficial apps or to be more
            specific "electron apps".
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import AlertIcon from "@renderer/assets/icons/alert-triangle.svg";
import ControlBar from "@renderer/components/ControlBar.vue";
</script>

<style lang="scss">
html,
body {
  @apply overflow-hidden;
}
</style>

// src/renderer/src/routes/youtube/login-notice.tsx
import { createFileRoute } from "@tanstack/react-router";
import AlertIcon from "@/assets/icons/alert-triangle.svg?react";
import { ControlBar } from "@/components/control-bar";

export const Route = createFileRoute("/youtube/login-notice")({
	component: LoginNoticePage,
});

function LoginNoticePage() {
	return (
		<div className="flex h-full flex-col overflow-hidden">
			<ControlBar title="Google - Login" divider={<span>&nbsp;</span>} />
			<div className="pointer-events-none flex flex-auto flex-shrink-0 select-none items-center bg-blue-500 text-sm text-white">
				<div className="container flex items-start justify-center gap-2">
					<AlertIcon className="mt-1 size-4 flex-shrink-0" />
					<div className="flex flex-col leading-tight">
						<p>
							If there are any issues logging in, press <strong>try again</strong> until it works.
						</p>
						<p className="break-words">
							This is happening due to google tightening security on unofficial apps or to be more specific "electron apps".
						</p>
					</div>
				</div>
			</div>
		</div>
	);
}
