// src/renderer/src/views/mini-player/index.vue
<template>
  <div class="h-full absolute inset-0 overflow-hidden bg-black flex flex-col"
       :style="{
        ...((accentColor &&
          showWinBorder &&
          (showWinBorder === 'win11'
            ? { borderWidth: '2.5px', borderStyle: 'solid' }
            : showWinBorder
              ? { borderWidth: '1px', borderStyle: 'solid' }
              : {})) ||
          {}),
        ...((accentColor &&
          (state.maximized || state.fullScreen || state.y === 0
            ? { borderRadius: '0px', borderWidth: '0px' }
            : showWinBorder === 'win11'
              ? { borderRadius: '8px' }
              : state.platform.isMacOS
                ? { borderRadius: '12px' }
                : { borderRadius: '6px' })) ||
          {}),
        ...(accentColor && showWinBorder ? { borderColor: `${accentColor}` } : {}),
      }">
    <div class="relative">
      <control-bar title="Mini Player"
                   class="bg-transparent border-b-0 z-20 pl-4 relative group">
        <template #icon>
          <MiniPlayerIcon class="antialiased" />
        </template>
        <template #divider>
          <button class="control-button relative w-4 group-hover:w-auto group-hover:px-2 group-hover:space-x-2 h-4 hover:bg-white/5"
                  @click="() => toggleStayTop()">
            <LockIcon v-if="isTop"
                      class="group-hover:opacity-100"></LockIcon>
            <UnLockIcon v-else
                        class="opacity-60"></UnLockIcon>
            <span class="hidden group-hover:flex text-sm">Stay on Top</span>
          </button>
        </template>
      </control-bar>
      <div class="absolute h-48 inset-x-0 bg-gradient-to-b from-black to-black/0 -top-32 z-10"></div>
    </div>
    <div class="absolute inset-0">
      <div v-if="thumbnail && accentColor"
           class="absolute inset-0 opacity-[.25]"
           :style="{
            backgroundColor: `${accentColor}`,
          }"></div>
      <div v-if="thumbnail"
           class="absolute inset-0 bg-no-repeat bg-cover bg-center opacity-[.25] scale-125 blur-[8px]"
           :style="{ backgroundImage: `url(${thumbnail})` }"></div>
    </div>
    <div class="flex flex-col flex-1">
      <div class="flex flex-col relative z-10 px-6 flex-1 centeronscreen">
        <div class="flex items-start space-x-6">
          <div class="track-thumbnail flex flex-shrink-0 items-center shadow justify-center relative">
            <template v-if="trackBusy">
              <div class="absolute inset-0 flex items-center justify-center z-10 rounded-[inherit] overflow-hidden">
                <div class="absolute inset-0 bg-black/50 z-[1]"></div>
                <div class="absolute inset-0 bg-zinc-800/80 z-[2]"
                     :style="{
                      ...(accentColor ? { backgroundColor: `${accentColor}20` } : {}),
                    }"></div>
                <Spinner size="lg"
                         class="z-[5]" />
              </div>
            </template>
            <template v-if="thumbnail">
              <div v-if="accentColor"
                   class="absolute inset-0 rounded-[inherit] z-[1]"
                   :style="{
                    boxShadow: `10px 12px 12px -2px ${accentColor}50, 0 0 0 .1rem ${accentColor}`,
                  }"></div>
              <div v-if="accentColor"
                   class="absolute -inset-2 rounded-xl z-[2]"
                   :style="{
                    backgroundImage: `linear-gradient(${accentColor}a0, ${accentColor}00, ${accentColor}10, ${accentColor}f0)`,
                  }"></div>
              <div class="absolute inset-0 rounded-[inherit] overflow-hidden">
                <img class="absolute inset-0 h-full w-full object-center object-cover opacity-[.5] scale-[1.12] blur-[4px] z-[5]"
                     :src="thumbnail"
                     alt=""
                     loading="lazy"
                     @load="handleAccent" />
              </div>
              <img :src="thumbnail"
                   alt=""
                   class="w-full object-center object-contain z-[6] rounded-[inherit]"
                   loading="lazy" />
            </template>
            <div v-else
                 class="absolute inset-0 flex items-center justify-center rounded-[inherit]">
              <MiniPlayerIcon class="w-24 h-24 md:w-40 md:h-40 text-zinc-50"
                              :style="{
                                ...(accentColor ? { color: accentColor } : {}),
                              }" />
            </div>
          </div>
          <div class="flex flex-col flex-1 h-full truncate">
            <div v-if="track?.video"
                 class="min-w-0 flex-auto space-y-1 font-semibold truncate">
              <h2 class="text-zinc-50 text-lg truncate">{{ track.video.title }}</h2>
              <p class="text-zinc-400 text-sm md:text-base lg:text-lg leading-6 truncate"> by {{ track.video.author }} </p>
              <div v-if="time"
                   class="text-zinc-400 text-sm space-x-1 flex items-center whitespace-pre">
                <p class="track-status-time tabular-nums">{{ time[0] }}</p>
                <span>/</span>
                <p class="track-status-time tabular-nums">{{ time[1] }}</p>
              </div>
            </div>
            <div class="flex items-center space-x-2 mt-auto flex-shrink-0">
              <button v-if="playState?.disliked !== undefined"
                      type="button"
                      class="player-btn"
                      :class="{ active: !!playState?.disliked }"
                      :disabled="trackBusy"
                      aria-label="Dislike"
                      :style="{
                        ...(accentColor && !!playState?.disliked
                          ? { color: accentColor, stroke: '#fff' }
                          : {}),
                      }"
                      @click="dislikeToggle">
                <LikeIcon class="rotate-180" />
              </button>
              <button v-if="playState?.liked !== undefined"
                      type="button"
                      class="player-btn"
                      :class="{ active: !!playState?.liked }"
                      :disabled="trackBusy"
                      :style="{
                        ...(accentColor && !!playState?.liked
                          ? { color: accentColor, stroke: '#fff' }
                          : {}),
                      }"
                      aria-label="Like"
                      @click="likeToggle">
                <LikeIcon />
              </button>
              <button :class="{
                'player-btn relative size-8 p-1': true,
                'opacity-70 btn-disabled': lastFMLoading
              }"
                      v-if="lastFM.connected"
                      @click="authorizeLastFM">
                <template v-if="lastFM.connected && !lastFM.error && lastFMState !== null">
                  <Spinner size="sm"
                           v-if="typeof lastFMState === 'string'" />
                  <CheckIcon v-else-if="lastFMState === true"
                             class="text-green-500" />
                  <AlertCircleIcon v-else-if="lastFMState === false"
                                   class="text-red-500" />
                </template>
                <LastFMIcon :class="{
                  'text-green-500': lastFM.connected && !lastFM.error,
                  'text-red-500': lastFM.error,
                }"
                            v-else></LastFMIcon>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="flex flex-col relative z-10">
        <div v-if="time"
             class="group pt-4 -mt-4 cursor-pointer"
             @click="setCurrentTime">
          <div ref="progressHandle"
               class="h-1 group-hover:h-2 bg-white transition-all ease-in-out duration-150"
               :style="{
                width: `${time[2]}%`,
                maxWidth: '100%',
                ...(accentColor ? { backgroundColor: accentColor } : {}),
              }"></div>
        </div>
        <div class="bg-zinc-50/5 mt-auto text-zinc-200 flex items-center h-16">
          <div class="flex-auto flex items-center justify-evenly">
            <button type="button"
                    class="player-btn"
                    :disabled="trackBusy"
                    aria-label="Previous"
                    @click="prev">
              <PrevIcon />
            </button>
            <button type="button"
                    class="player-btn"
                    :disabled="trackBusy"
                    aria-label="Rewind 10 seconds"
                    @click="() => backward()">
              <BackwardIcon />
            </button>
          </div>
          <button type="button"
                  class="player-btn-hero"
                  :style="{
                    ...(accentColor ? { borderColor: accentColor } : {}),
                  }"
                  aria-label="Pause"
                  :disabled="trackBusy"
                  @click="() => (!playing ? play() : pause())">
            <div class="fill-icon fill-zinc-700">
              <template v-if="playing">
                <PauseIcon />
              </template>
              <template v-else>
                <PlayIcon />
              </template>
            </div>
          </button>
          <div class="flex-auto flex items-center justify-evenly">
            <button type="button"
                    class="player-btn"
                    :disabled="trackBusy"
                    aria-label="Skip 10 seconds"
                    @click="() => forward()">
              <ForwardIcon />
            </button>
            <button type="button"
                    class="player-btn"
                    :disabled="trackBusy"
                    aria-label="Next"
                    @click="next">
              <NextIcon />
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { TrackData } from "@main/utils/trackData";
import BackwardIcon from "@renderer/assets/icons/backward10.svg";
import ForwardIcon from "@renderer/assets/icons/forward10.svg";
import LastFMIcon from "@renderer/assets/icons/lastfm.svg";
import LikeIcon from "@renderer/assets/icons/like.svg";
import LockIcon from "@renderer/assets/icons/lock.svg";
import MiniPlayerIcon from "@renderer/assets/icons/mini-player.svg";
import NextIcon from "@renderer/assets/icons/next.svg";
import PauseIcon from "@renderer/assets/icons/pause.svg";
import PlayIcon from "@renderer/assets/icons/play.svg";
import PrevIcon from "@renderer/assets/icons/prev.svg";
import UnLockIcon from "@renderer/assets/icons/unlock.svg";
import ControlBar from "@renderer/components/ControlBar.vue";
import Spinner from "@renderer/components/Spinner.vue";
import { refLastFM } from "@renderer/lib/lastfm";
import { refIpc, refWindowState } from "@shared/utils/Ipc";
import { logger } from "@shared/utils/console";
import { intervalToDuration } from "date-fns";
import { clamp } from "lodash-es";
import { AlertCircleIcon, CheckIcon } from "lucide-vue-next";
import { computed, onMounted, ref, watch } from "vue";
const zeroPad = (num) => String(num).padStart(2, "0");
const createInterval = (dts: number[]): [string, number] => [
  dts
    .filter((p, i) => (i === 0 ? Boolean(p) : true))
    .map(zeroPad)
    .join(":"),
  dts.length,
];

const [track, setTrack] = refIpc<TrackData>("TRACK_CHANGE", {
  ignoreUndefined: true,
  defaultValue: null,
});
const accentColor = ref<string | null>(null);
const [state] = refWindowState();
const [playState, setPlayState] = refIpc<{
  playing: boolean;
  progress: number;
  duration: number;
  liked: boolean;
  disliked: boolean;
}>("TRACK_PLAYSTATE");
const showWinBorder = ref<boolean | "win11">(false);
const trackBusy = ref(false);
const isTop = ref(false);
onMounted(() => {
  document.title = `YouTube Music - Mini Player`;
  Promise.all([
    window.ipcRenderer.invoke("api/track"),
    window.ipcRenderer.invoke("api/track/state"),
    window.process.isWin11(),
    window.ipcRenderer.invoke("miniplayer.stayOnTop"),
    window.api.windowState(),
  ]).then(([trackData, playStateData, isWin11, stayTop, windowState]) => {
    setTrack(trackData);
    setPlayState(playStateData);
    showWinBorder.value = window.process.platform === "win32" ? (isWin11 ? "win11" : true) : windowState.platform.isMacOS;
    isTop.value = stayTop;
    console.log({
      showWinBorder: showWinBorder.value,
      platform: window.process.platform,
      isWin11,
    });
  });
});
const { lastFM, lastFMLoading, lastFMState, authorizeLastFM } = refLastFM();
const progressHandle = ref<HTMLElement>(null);
let accentHandle: any;
const getCurrentAccent = (retry: number = 0) => {
  if (accentHandle) clearTimeout(accentHandle);
  window.ipcRenderer.invoke("api/track/accent").then((clr) => {
    if (!clr || retry > 2) accentColor.value = clr || null;
    else accentColor.value = clr;
    console.log("Accent", clr);
    if (!clr) accentHandle = setTimeout(getCurrentAccent.bind(this, retry + 1), 500);
  });
};
function next() {
  trackBusy.value = true;
  return window.ipcRenderer
    .invoke("api/track/next")
    .finally(() => {
      trackBusy.value = false;
    })
    .then(() => {
      playState.value.progress = 0;
    });
}
function prev() {
  trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/prev").finally(() => {
    trackBusy.value = false;
    playState.value.progress = 0;
  });
}
function forward(time = 10000) {
  trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/forward", { time }).finally(() => {
    trackBusy.value = false;
  });
}
function backward(time = 10000) {
  trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/backward", { time }).finally(() => {
    trackBusy.value = false;
  });
}
function pause() {
  // trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/pause").finally(() => {
    // trackBusy.value = false;
  });
}
function play() {
  // trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/play").finally(() => {
    // trackBusy.value = false;
  });
}
function dislikeToggle() {
  if (typeof playState.value?.disliked !== "boolean") return;
  trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/dislike", !playState.value.disliked).finally(() => {
    trackBusy.value = false;
  });
}
function likeToggle() {
  if (typeof playState.value?.liked !== "boolean") return;
  trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/like", !playState.value.liked).finally(() => {
    trackBusy.value = false;
  });
}
function handleAccent(ev: Parameters<HTMLImageElement["onload"]>[0]) {
  const src = (ev.target as HTMLImageElement).src;
  if (src) {
    getCurrentAccent();
  }
}
function setCurrentTime(ev: MouseEvent) {
  if (trackBusy.value) return;
  if (!playState.value) return;
  const [el, progress] = [ev.currentTarget as HTMLDivElement, progressHandle.value];
  const percSelected = ev.x / el.clientWidth;
  const { duration } = playState.value;
  const seekTime = clamp(duration * percSelected, 0, duration) * 1000;
  console.log({
    percentage: percSelected,
    value: seekTime / 1000,
    duration,
  });
  trackBusy.value = true;
  return window.ipcRenderer.invoke("api/track/seek", { time: seekTime, type: "seek" }).finally(() => {
    trackBusy.value = false;
  });
}
async function toggleStayTop() {
  const result = await window.api.action("miniplayer.stayOnTop");
  isTop.value = result;
}
function action(actionParam, ...params) {
  return window.api.action(actionParam, ...params);
}
function invoke(invokeParam, ...params) {
  return window.api.invoke(invokeParam, ...params);
}
const thumbnail = computed(() => {
  return track.value?.meta?.thumbnail;
});
const playing = computed(() => {
  return !!playState.value?.playing;
});

const time = computed((): [string, string, number] => {
  const { duration, progress } = playState.value ?? {};
  if (typeof duration !== "number" || typeof progress !== "number") return null;
  const [current] = (({ hours, minutes, seconds }) => createInterval([hours, minutes, seconds]))(
    intervalToDuration({
      start: duration * 1000 - (progress > duration ? duration : Math.floor(progress)) * 1000,
      end: duration * 1000,
    }),
  );
  const [end, endPad] = (({ hours, minutes, seconds }) => createInterval([hours, minutes, seconds]))(intervalToDuration({ start: 0, end: duration * 1000 })) as [string, number];
  const timePad = endPad * 2;
  const percentage = ((progress > duration ? duration : progress) / duration) * 100;
  return [current.padEnd(timePad), end.padStart(timePad), percentage];
});
watch(state, (windowState) => logger.debug(windowState && { ...windowState }));
</script>
<style lang="scss">
.track-status-time {
  @apply min-w-[40px];
}

.player-btn {
  @apply h-10 w-10 text-zinc-200 p-2 cursor-pointer flex items-center justify-center rounded-lg transition ease-in-out duration-100;

  &:hover {
    @apply bg-zinc-50/5;
  }

  &:active {
    @apply transform-gpu scale-95 bg-zinc-50/10;
  }

  &:disabled,
  &.disabled {
    @apply opacity-60 scale-100;
  }

  &.active {
    svg {
      @apply fill-current;

      path {
        @apply stroke-inherit;
      }
    }
  }

  &-hero {
    @apply border border-zinc-600 text-zinc-200 flex-none mx-auto w-10 h-10 rounded-full ring-1 ring-zinc-900/5 shadow-md flex items-center justify-center transition ease-in-out duration-100;

    svg {
      @apply h-6 w-6;
    }

    &:disabled,
    &.disabled {
      @apply opacity-60 scale-100;
    }

    &:active {
      @apply transform-gpu scale-95 border-zinc-50/90;
    }
  }
}

.fill-icon {
  svg {
    @apply fill-current;

    path {
      @apply stroke-transparent;
    }
  }
}

.centeronscreen {
  @apply flex flex-col justify-center;
}

.track-thumbnail {
  @apply flex-none rounded-lg bg-zinc-800;

  height: calc(100vh - 10rem);
  width: calc(100vh - 10rem);
  max-width: calc(100vw - 16rem);
  max-height: calc(100vw - 16rem);

  img {
    @apply object-cover object-center;
  }
}
</style>

// apps/ytmdesktop2/src/renderer/src/routes/miniplayer.tsx
import type { TrackData } from "@shared/track/trackData";
import { createFileRoute } from "@tanstack/react-router";
import { cva, type VariantProps } from "class-variance-authority";
import { intervalToDuration } from "date-fns";
import { clamp } from "lodash-es";
import { AlertCircleIcon, CheckIcon } from "lucide-react";
import { type ButtonHTMLAttributes, type CSSProperties, type MouseEvent, useCallback, useMemo, useRef, useState } from "react";
import BackwardIcon from "@/assets/icons/backward10.svg?react";
import ForwardIcon from "@/assets/icons/forward10.svg?react";
import LastFMIcon from "@/assets/icons/lastfm.svg?react";
import LikeIcon from "@/assets/icons/like.svg?react";
import LockIcon from "@/assets/icons/lock.svg?react";
import MiniPlayerIcon from "@/assets/icons/mini-player.svg?react";
import NextIcon from "@/assets/icons/next.svg?react";
import PauseIcon from "@/assets/icons/pause.svg?react";
import PlayIcon from "@/assets/icons/play.svg?react";
import PrevIcon from "@/assets/icons/prev.svg?react";
import UnLockIcon from "@/assets/icons/unlock.svg?react";
import { ControlBar } from "@/components/control-bar";
import { Spinner } from "@/components/ui/spinner";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useLastFm } from "@/hooks/use-lastfm";
import { useWindowState } from "@/hooks/use-settings";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/miniplayer")({
	component: MiniPlayerPage,
});

interface PlayState {
	playing: boolean;
	progress: number;
	duration: number;
	liked: boolean;
	disliked: boolean;
}

const playerButtonVariants = cva(
	[
		"inline-flex shrink-0 cursor-pointer items-center justify-center text-zinc-200 transition-all duration-100 ease-in-out",
		"disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-60 disabled:transform-none",
		"[&_svg]:pointer-events-none [&_svg]:shrink-0",
	].join(" "),
	{
		variants: {
			variant: {
				default: [
					"size-10 rounded-lg p-2",
					"enabled:hover:bg-zinc-50/5",
					"enabled:active:scale-95 enabled:active:bg-zinc-50/10",
					"data-[active=true]:[&_svg]:fill-current data-[active=true]:[&_svg_path]:stroke-inherit",
				].join(" "),
				hero: [
					"mx-auto size-10 shrink-0 rounded-full border border-zinc-600 shadow-sm",
					"enabled:active:scale-95 enabled:active:border-zinc-50/90",
					"[&_svg]:size-6",
				].join(" "),
			},
		},
		defaultVariants: {
			variant: "default",
		},
	},
);

type PlayerButtonProps = ButtonHTMLAttributes<HTMLButtonElement> &
	VariantProps<typeof playerButtonVariants> & {
		active?: boolean;
	};

function PlayerButton({ className, variant, active, type = "button", ...props }: PlayerButtonProps) {
	return (
		<button
			type={type}
			data-active={active ? "true" : undefined}
			className={cn(playerButtonVariants({ variant }), className)}
			{...props}
		/>
	);
}

const zeroPad = (num: number | undefined): string => String(num ?? 0).padStart(2, "0");

const createInterval = (dts: (number | undefined)[]): [string, number] => [
	dts
		.filter((p, i) => (i === 0 ? Boolean(p) : true))
		.map(zeroPad)
		.join(":"),
	dts.length,
];

function MiniPlayerPage() {
	const utils = trpc.useUtils();
	const [track, setTrack] = useState<TrackData | null>(null);
	const [playState, setPlayState] = useState<PlayState | undefined>();
	const [state] = useWindowState();
	const { lastFM, lastFMLoading, lastFMState, authorizeLastFM } = useLastFm();

	const [accentColor, setAccentColor] = useState<string | null>(null);
	const [trackBusy, setTrackBusy] = useState(false);
	const [stayOnTopLocal, setStayOnTopLocal] = useState<boolean | undefined>();

	const progressHandleRef = useRef<HTMLDivElement>(null);
	const accentHandleRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
	const playStateRef = useRef(playState);
	playStateRef.current = playState;

	document.title = "YouTube Music - Mini Player";

	const { data: isWin11 } = trpc.app.isWin11.useQuery();
	const { data: isStayOnTop } = trpc.window.isStayOnTop.useQuery();

	const { mutateAsync: next } = trpc.track.next.useMutation();
	const { mutateAsync: prev } = trpc.track.prev.useMutation();
	const { mutateAsync: forward } = trpc.track.forward.useMutation();
	const { mutateAsync: backward } = trpc.track.backward.useMutation();
	const { mutateAsync: pause } = trpc.track.pause.useMutation();
	const { mutateAsync: play } = trpc.track.play.useMutation();
	const { mutateAsync: dislike } = trpc.track.dislike.useMutation();
	const { mutateAsync: like } = trpc.track.like.useMutation();
	const { mutateAsync: seek } = trpc.track.seek.useMutation();
	const { mutateAsync: stayOnTop } = trpc.window.stayOnTop.useMutation();

	trpc.track.current.useQuery(undefined, {
		onSuccess: (trackData) => setTrack((trackData as TrackData | null) ?? null),
	});
	trpc.track.onTrack.useSubscription(undefined, {
		onData: (trackData) => setTrack((trackData as TrackData | null) ?? null),
	});
	trpc.track.state.useQuery(undefined, {
		onSuccess: (playStateData) => {
			if (playStateData) setPlayState(playStateData as PlayState);
		},
	});
	trpc.track.onPlayState.useSubscription(undefined, {
		onData: (playStateData) => {
			if (playStateData) setPlayState(playStateData as PlayState);
		},
	});

	const isTop = stayOnTopLocal ?? !!isStayOnTop;
	const showWinBorder = useMemo((): boolean | "win11" => {
		if (window.app.platform === "win32") {
			if (isWin11 === undefined) return false;
			return isWin11 ? "win11" : true;
		}
		return !!state?.platform?.isMacOS;
	}, [isWin11, state?.platform?.isMacOS]);

	const getCurrentAccent = useCallback(
		(retry = 0) => {
			if (accentHandleRef.current) clearTimeout(accentHandleRef.current);
			utils.track.accent.fetch().then((clr) => {
				if (!clr || retry > 2) setAccentColor(clr || null);
				else setAccentColor(clr);
				if (!clr) accentHandleRef.current = setTimeout(() => getCurrentAccent(retry + 1), 500);
			});
		},
		[utils],
	);

	function handleNext() {
		setTrackBusy(true);
		return next()
			.finally(() => {
				setTrackBusy(false);
			})
			.then(() => {
				if (playStateRef.current) setPlayState({ ...playStateRef.current, progress: 0 });
			});
	}

	function handlePrev() {
		setTrackBusy(true);
		return prev().finally(() => {
			setTrackBusy(false);
			if (playStateRef.current) setPlayState({ ...playStateRef.current, progress: 0 });
		});
	}

	function handleForward(time = 10000) {
		setTrackBusy(true);
		return forward({ time }).finally(() => {
			setTrackBusy(false);
		});
	}

	function handleBackward(time = 10000) {
		setTrackBusy(true);
		return backward({ time }).finally(() => {
			setTrackBusy(false);
		});
	}

	function dislikeToggle() {
		if (typeof playStateRef.current?.disliked !== "boolean") return;
		setTrackBusy(true);
		return dislike(!playStateRef.current.disliked).finally(() => {
			setTrackBusy(false);
		});
	}

	function likeToggle() {
		if (typeof playStateRef.current?.liked !== "boolean") return;
		setTrackBusy(true);
		return like(!playStateRef.current.liked).finally(() => {
			setTrackBusy(false);
		});
	}

	const handleAccent = useCallback(
		(ev: React.SyntheticEvent<HTMLImageElement>) => {
			const src = ev.currentTarget.src;
			if (src) getCurrentAccent();
		},
		[getCurrentAccent],
	);

	function setCurrentTime(ev: MouseEvent<HTMLDivElement>) {
		if (trackBusy) return;
		const current = playStateRef.current;
		if (!current) return;
		const el = ev.currentTarget;
		const percSelected = ev.clientX / el.clientWidth;
		const duration = current.duration || Number(track?.meta?.duration) || 0;
		if (duration <= 0) return;
		const seekTime = clamp(duration * percSelected, 0, duration) * 1000;
		setTrackBusy(true);
		void seek({ time: seekTime, type: "seek" })
			.then(() => {
				setPlayState({ ...current, progress: seekTime / 1000, duration });
			})
			.finally(() => {
				setTrackBusy(false);
			});
	}

	async function toggleStayTop() {
		const result = await stayOnTop();
		setStayOnTopLocal(result);
	}

	const thumbnail = track?.meta?.thumbnail;
	const playing = !!playState?.playing;

	const time = useMemo((): [string, string, number] | null => {
		const progress = playState?.progress;
		const duration = playState?.duration || Number(track?.meta?.duration) || 0;
		if (typeof progress !== "number" || duration <= 0) return null;
		const elapsed = Math.max(0, Math.min(Math.floor(progress), Math.floor(duration)));
		const [current] = (({ hours, minutes, seconds }) => createInterval([hours, minutes, seconds]))(
			intervalToDuration({ start: 0, end: elapsed * 1000 }),
		);
		const [end, endPad] = (({ hours, minutes, seconds }) => createInterval([hours, minutes, seconds]))(
			intervalToDuration({ start: 0, end: duration * 1000 }),
		) as [string, number];
		const timePad = endPad * 2;
		const percentage = (elapsed / duration) * 100;
		return [current.padEnd(timePad), end.padStart(timePad), percentage];
	}, [playState, track?.meta?.duration]);

	const rootStyle = useMemo((): CSSProperties => {
		const style: CSSProperties = {};
		if (accentColor && showWinBorder) {
			style.borderWidth = showWinBorder === "win11" ? "2.5px" : "1px";
			style.borderStyle = "solid";
			style.borderColor = accentColor;
		}
		if (accentColor) {
			if (state.maximized || state.fullScreen || state.y === 0) {
				style.borderRadius = "0px";
				style.borderWidth = "0px";
			} else if (showWinBorder === "win11") {
				style.borderRadius = "8px";
			} else if (state.platform?.isMacOS) {
				style.borderRadius = "12px";
			} else {
				style.borderRadius = "6px";
			}
		}
		return style;
	}, [accentColor, showWinBorder, state]);

	return (
		<div className="absolute inset-0 flex h-full flex-col overflow-hidden bg-black" style={rootStyle}>
			<style>{`
				.track-status-time { min-width: 40px; }
				.fill-icon svg { fill: currentColor; }
				.fill-icon svg path { stroke: transparent; }
				.track-thumbnail {
					flex: none; border-radius: 0.5rem; background-color: rgb(39 39 42);
					height: calc(100vh - 10rem); width: calc(100vh - 10rem);
					max-width: calc(100vw - 16rem); max-height: calc(100vw - 16rem);
				}
				.track-thumbnail img { object-fit: cover; object-position: center; }
			`}</style>

			<div className="absolute inset-0">
				{thumbnail && accentColor && (
					<div className="absolute inset-0 opacity-[.25]" style={{ backgroundColor: accentColor }} />
				)}
				{thumbnail && (
					<div
						className="absolute inset-0 scale-125 bg-cover bg-center bg-no-repeat opacity-[.25] blur-[8px]"
						style={{ backgroundImage: `url(${thumbnail})` }}
					/>
				)}
			</div>

			<div className="absolute inset-x-0 top-0 z-30">
				<ControlBar
					title="Mini Player"
					icon={<MiniPlayerIcon className="antialiased" />}
					className="border-b-0 bg-transparent pl-4 text-zinc-50 [&_.drag]:text-zinc-50 [&>div>div]:text-zinc-50"
					divider={
						<Tooltip>
							<TooltipTrigger
								render={
									<button
										type="button"
										className="control-button"
										aria-label={isTop ? "Disable stay on top" : "Stay on top"}
										onClick={() => void toggleStayTop()}
									>
										{isTop ? <LockIcon /> : <UnLockIcon className="opacity-70" />}
									</button>
								}
							/>
							<TooltipContent side="bottom">{isTop ? "Disable stay on top" : "Stay on top"}</TooltipContent>
						</Tooltip>
					}
				/>
				<div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-24 bg-linear-to-b from-black/60 to-transparent" />
			</div>

			<div className="relative z-10 flex min-h-0 flex-1 flex-col pt-10">
				<div className="centeronscreen relative z-10 flex flex-1 flex-col justify-center px-6">
					<div className="flex items-start space-x-6">
						<div className="track-thumbnail relative flex flex-shrink-0 items-center justify-center shadow">
							{trackBusy && (
								<div className="absolute inset-0 z-10 flex items-center justify-center overflow-hidden rounded-[inherit]">
									<div className="absolute inset-0 z-[1] bg-black/50" />
									<div
										className="absolute inset-0 z-[2] bg-zinc-800/80"
										style={accentColor ? { backgroundColor: `${accentColor}20` } : undefined}
									/>
									<Spinner className="z-[5] size-8" />
								</div>
							)}
							{thumbnail ? (
								<>
									{accentColor && (
										<div
											className="absolute inset-0 z-[1] rounded-[inherit]"
											style={{
												boxShadow: `10px 12px 12px -2px ${accentColor}50, 0 0 0 .1rem ${accentColor}`,
											}}
										/>
									)}
									{accentColor && (
										<div
											className="absolute -inset-2 z-[2] rounded-xl"
											style={{
												backgroundImage: `linear-gradient(${accentColor}a0, ${accentColor}00, ${accentColor}10, ${accentColor}f0)`,
											}}
										/>
									)}
									<div className="absolute inset-0 overflow-hidden rounded-[inherit]">
										<img
											className="absolute inset-0 z-[5] h-full w-full scale-[1.12] object-cover object-center opacity-[.5] blur-[4px]"
											src={thumbnail}
											alt=""
											loading="lazy"
											onLoad={handleAccent}
										/>
									</div>
									<img
										src={thumbnail}
										alt=""
										className="z-[6] w-full rounded-[inherit] object-contain object-center"
										loading="lazy"
									/>
								</>
							) : (
								<div className="absolute inset-0 flex items-center justify-center rounded-[inherit]">
									<MiniPlayerIcon
										className="h-24 w-24 text-zinc-50 md:h-40 md:w-40"
										style={accentColor ? { color: accentColor } : undefined}
									/>
								</div>
							)}
						</div>

						<div className="flex h-full flex-1 truncate flex-col">
							{track?.video && (
								<div className="min-w-0 flex-auto space-y-1 truncate font-semibold">
									<h2 className="truncate text-lg text-zinc-50">{track.video.title}</h2>
									<p className="truncate text-sm leading-6 text-zinc-400 md:text-base lg:text-lg">
										{" "}
										by {track.video.author}{" "}
									</p>
									{time && (
										<div className="flex items-center space-x-1 whitespace-pre text-sm text-zinc-400">
											<p className="track-status-time tabular-nums">{time[0]}</p>
											<span>/</span>
											<p className="track-status-time tabular-nums">{time[1]}</p>
										</div>
									)}
								</div>
							)}
							<div className="mt-auto flex flex-shrink-0 items-center space-x-2">
								{playState?.disliked !== undefined && (
									<PlayerButton
										active={!!playState?.disliked}
										disabled={trackBusy}
										aria-label="Dislike"
										style={
											accentColor && !!playState?.disliked
												? { color: accentColor, stroke: "#fff" }
												: undefined
										}
										onClick={dislikeToggle}
									>
										<LikeIcon className="rotate-180" />
									</PlayerButton>
								)}
								{playState?.liked !== undefined && (
									<PlayerButton
										active={!!playState?.liked}
										disabled={trackBusy}
										aria-label="Like"
										style={
											accentColor && !!playState?.liked
												? { color: accentColor, stroke: "#fff" }
												: undefined
										}
										onClick={likeToggle}
									>
										<LikeIcon />
									</PlayerButton>
								)}
								{lastFM.connected && (
									<PlayerButton
										className="relative size-8 p-1"
										disabled={lastFMLoading || trackBusy}
										aria-label="Last.fm"
										onClick={authorizeLastFM}
									>
										{lastFM.connected && !lastFM.error && lastFMState !== null ? (
											typeof lastFMState === "string" ? (
												<Spinner className="size-3" />
											) : lastFMState === true ? (
												<CheckIcon className="text-green-500" />
											) : lastFMState === false ? (
												<AlertCircleIcon className="text-red-500" />
											) : null
										) : (
											<LastFMIcon
												className={cn(
													lastFM.connected && !lastFM.error && "text-green-500",
													lastFM.error && "text-red-500",
												)}
											/>
										)}
									</PlayerButton>
								)}
							</div>
						</div>
					</div>
				</div>

				<div className="relative z-10 flex flex-col">
					{time && (
						<div className="group -mt-4 cursor-pointer pt-4" onClick={setCurrentTime}>
							<div
								ref={progressHandleRef}
								className="h-1 bg-white transition-all duration-150 ease-in-out group-hover:h-2"
								style={{
									width: `${time[2]}%`,
									maxWidth: "100%",
									...(accentColor ? { backgroundColor: accentColor } : {}),
								}}
							/>
						</div>
					)}
					<div className="mt-auto flex h-16 items-center bg-zinc-50/5 text-zinc-200">
						<div className="flex flex-auto items-center justify-evenly">
							<PlayerButton disabled={trackBusy} aria-label="Previous" onClick={handlePrev}>
								<PrevIcon />
							</PlayerButton>
							<PlayerButton disabled={trackBusy} aria-label="Rewind 10 seconds" onClick={() => void handleBackward()}>
								<BackwardIcon />
							</PlayerButton>
						</div>
						<PlayerButton
							variant="hero"
							style={accentColor ? { borderColor: accentColor } : undefined}
							aria-label={playing ? "Pause" : "Play"}
							disabled={trackBusy}
							onClick={() => void (!playing ? play() : pause())}
						>
							<div className="fill-icon fill-zinc-700">{playing ? <PauseIcon /> : <PlayIcon />}</div>
						</PlayerButton>
						<div className="flex flex-auto items-center justify-evenly">
							<PlayerButton disabled={trackBusy} aria-label="Skip 10 seconds" onClick={() => void handleForward()}>
								<ForwardIcon />
							</PlayerButton>
							<PlayerButton disabled={trackBusy} aria-label="Next" onClick={handleNext}>
								<NextIcon />
							</PlayerButton>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
