// apps/ytmdesktop2/src/renderer/src/components/toolbar-options.tsx
import { AlertCircleIcon, CheckIcon, DownloadIcon } from "lucide-react";
import DevIcon from "@/assets/icons/chip.svg?react";
import RPCIcon from "@/assets/icons/discord-rpc.svg?react";
import HomeIcon from "@/assets/icons/home.svg?react";
import LastFMIcon from "@/assets/icons/lastfm.svg?react";
import MiniPlayerIcon from "@/assets/icons/mini-player.svg?react";
import RefreshIcon from "@/assets/icons/refresh.svg?react";
import { Spinner } from "@/components/ui/spinner";
import { useDiscord } from "@/hooks/use-discord";
import { useLastFm } from "@/hooks/use-lastfm";
import { useMiniPlayer } from "@/hooks/use-miniplayer";
import { useNavigation } from "@/hooks/use-navigation";
import { useSettingsState } from "@/hooks/use-settings";
import { useTrackState } from "@/hooks/use-track";
import { useUpdater } from "@/hooks/use-updater";
import { trpc } from "@/lib/trpc";

export function ToolbarOptions() {
	const { lastFM, lastFMState, lastFMLoading, authorizeLastFM } = useLastFm();
	const { connected: discordConnected, loading: discordLoading, error: discordConnectionError, enabled: discordEnabled, toggle: toggleDiscord } = useDiscord();
	const { isHome, home, devTools } = useNavigation();
	const { state: miniPlayer, open: openMiniPlayer } = useMiniPlayer();
	const playState = useTrackState();
	const { updateInfo, downloaded: updateDownloaded, checking: updateChecking, status, check } = useUpdater();
	const [isDev] = useSettingsState<boolean>("app.enableDev", false);
	const { mutateAsync: openWindow } = trpc.app.openWindow.useMutation();

	return (
		<div className="flex flex-row items-center gap-2">
			<button
				type="button"
				className={`control-button relative h-4 ${lastFMLoading ? "opacity-70" : ""} ${lastFM?.name ? "!w-auto flex gap-2.5 items-center px-1.5" : "w-4"}`}
				onClick={authorizeLastFM}
			>
				{lastFM?.connected && !lastFM?.error && lastFMState !== null ? (
					typeof lastFMState === "string" ? (
						<Spinner className="size-3" />
					) : lastFMState === true ? (
						<CheckIcon className="text-green-500" />
					) : (
						<AlertCircleIcon className="text-red-500" />
					)
				) : (
					<LastFMIcon className={lastFM?.connected && !lastFM?.error ? "text-green-500" : lastFM?.error ? "text-red-500" : undefined} />
				)}
				{lastFM?.name && <span className="text-sm text-gray-100">{lastFM.name}</span>}
			</button>
			{!isHome && (
				<button type="button" className="control-button relative size-4" onClick={() => void home()}>
					<HomeIcon />
				</button>
			)}
			<button type="button" className="control-button relative size-4" disabled={!!updateChecking} onClick={() => void check()}>
				{status === "checking" && !updateInfo ? (
					<Spinner className="size-3" />
				) : updateInfo ? (
					<DownloadIcon className={status === "ready" || updateDownloaded ? "text-green-500" : "animate-pulse"} />
				) : (
					<RefreshIcon />
				)}
			</button>
			{isDev && (
				<button type="button" className="control-button relative size-4" onClick={() => void devTools()}>
					<DevIcon />
				</button>
			)}
			<button
				type="button"
				className={`control-button relative size-4 ${miniPlayer ? (miniPlayer.active ? "opacity-100" : "opacity-70") : ""}`}
				disabled={!playState}
				onClick={() => void openMiniPlayer()}
			>
				<MiniPlayerIcon />
			</button>
			<button type="button" className="control-button relative" onClick={toggleDiscord}>
				<RPCIcon
					className={
						discordConnectionError && discordEnabled
							? "text-red-500"
							: discordEnabled || discordConnectionError
								? "opacity-100"
								: "opacity-70"
					}
				/>
				{discordConnected && !discordConnectionError && !discordLoading && (
					<div className="absolute top-0 right-0 flex size-3 items-center justify-center rounded-full bg-green-500 p-0.5">
						<svg xmlns="http://www.w3.org/2000/svg" className="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
							<polyline points="20 6 9 17 4 12" />
						</svg>
					</div>
				)}
				{discordLoading && (
					<div className="absolute top-0 right-0 flex size-3 items-center justify-center rounded-full bg-gray-600 p-0.5">
						<Spinner className="size-2" />
					</div>
				)}
			</button>
			<button type="button" className="control-button" onClick={() => void openWindow("settingsWindow")}>
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
					<path
						fillRule="evenodd"
						d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
						clipRule="evenodd"
					/>
				</svg>
			</button>
		</div>
	);
}

// src/renderer/src/views/youtube/toolbar-options.vue
<template>
  <div class="flex flex-row items-center space-x-2">
    <button :class="{
      'control-button relative h-4': true,
      'opacity-70 btn-disabled': lastFMLoading,
      [lastFM.name ? '!w-auto flex space-x-2.5 items-center px-1.5 ' : 'w-4']: true,
    }"
            @click="authorizeLastFM">
      <template v-if="lastFM.connected && !lastFM.error && lastFMState !== null">
        <Spinner size="sm"
                 v-if="typeof lastFMState === 'string'" />
        <CheckIcon v-else-if="lastFMState === true"
                   class="text-green-500" />
        <AlertCircleIcon v-else-if="lastFMState === false"
                         class="text-red-500" />
      </template>
      <LastFMIcon :class="{
        'text-green-500': lastFM.connected && !lastFM.error,
        'text-red-500': lastFM.error,
      }"
                  v-else></LastFMIcon>
      <span v-if="lastFM.name"
            :class="{ 'text-gray-100 text-sm': true }">{{ lastFM.name }}</span>
    </button>
    <button v-if="!isHome"
            class="control-button relative w-4 h-4"
            @click="() => action('nav.same-origin')">
      <HomeIcon></HomeIcon>
    </button>
    <button class="control-button relative w-4 h-4"
            :class="{ disabled: updateChecking }"
            :disabled="updateChecking"
            @click="() => checkUpdate()">
      <Spinner v-if="updateChecking && !updateInfo"
               size="sm" />
      <DownloadIcon v-else-if="updateInfo"
                    :class="{ 'animate-pulse': !updateDownloaded, 'text-green-500': updateDownloaded }"></DownloadIcon>
      <RefreshIcon v-else></RefreshIcon>
    </button>
    <button v-if="isDev"
            class="control-button relative w-4 h-4"
            @click="() => action('app.devTools')">
      <DevIcon></DevIcon>
    </button>
    <button class="control-button relative w-4 h-4"
            :disabled="!playState"
            :class="miniPlayer ? { 'opacity-100': miniPlayer?.active, 'opacity-70': !miniPlayer?.active } : {}
              "
            @click="() => action('app.miniPlayer')">
      <MiniPlayerIcon />
    </button>
    <button class="control-button relative"
            @click="() => toggleSetting('discord.enabled')">
      <RPCIcon :class="{ 'text-red-500': discordConnectionError && discordEnabled, 'opacity-100': discordEnabled || discordConnectionError, 'opacity-70': !discordEnabled || discordLoading }"></RPCIcon>
      <div v-if="discordConnected && !discordConnectionError && !discordLoading"
           class="p-0.5 rounded-full bg-green-500 absolute top-0 right-0 w-3 h-3 flex items-center justify-center">
        <svg xmlns="http://www.w3.org/2000/svg"
             class="w-4 h-4"
             viewBox="0 0 24 24"
             fill="none"
             stroke="currentColor"
             stroke-width="3"
             stroke-linecap="round"
             stroke-linejoin="round">
          <polyline points="20 6 9 17 4 12"></polyline>
        </svg>
      </div>
      <div v-else-if="discordLoading"
           class="p-0.5 rounded-full bg-gray-600 absolute top-0 right-0 w-3 h-3 flex items-center justify-center">
        <Spinner size="sm" />
      </div>
    </button>
    <button class="control-button"
            @click="onSettings">
      <svg xmlns="http://www.w3.org/2000/svg"
           viewBox="0 0 20 20"
           fill="currentColor">
        <path fill-rule="evenodd"
              d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
              clip-rule="evenodd" />
      </svg>
    </button>
  </div>
</template>
<script lang="ts" setup>
import IPC_EVENT_NAMES from "@main/utils/eventNames";
import DevIcon from "@renderer/assets/icons/chip.svg";
import RPCIcon from "@renderer/assets/icons/discord-rpc.svg";
import HomeIcon from "@renderer/assets/icons/home.svg";
import LastFMIcon from "@renderer/assets/icons/lastfm.svg";
import MiniPlayerIcon from "@renderer/assets/icons/mini-player.svg";
import RefreshIcon from "@renderer/assets/icons/refresh.svg";
import Spinner from "@renderer/components/Spinner.vue";
import { logger } from "@shared/utils/console";
import { refIpc } from "@shared/utils/Ipc";
import type { UpdateInfo } from "@shared/utils/updater";
import { AlertCircleIcon, CheckIcon, DownloadIcon } from "lucide-vue-next";
import { onMounted, ref } from "vue";

const discordConnectionMap = { ["discord.connected"]: true, ["discord.disconnected"]: false } as const;
const [discordLoading, setDiscordLoading] = refIpc("discord.loading", {
	defaultValue: false,
	mapper: () => true,
	ignoreUndefined: false,
});
const [discordConnected, setDiscordConnected] = refIpc(["discord.connected", "discord.disconnected"], {
	defaultValue: false,
	mapper: (data, name) => {
		return discordConnectionMap[name];
	},
	onTrigger(item, prev, { eventName }) {
		if (eventName === "discord.connected") {
			setDiscordConnectionError(null);
			setDiscordConnected(item);
			setDiscordLoading(false);
		}
	},
	ignoreUndefined: true,
});
const [discordConnectionError, setDiscordConnectionError] = refIpc(["discord.error"], {
	defaultValue: null,
	debug: true,
});
const [miniPlayer] = refIpc("miniplayer.state", {
	defaultValue: null,
	ignoreUndefined: true,
});
const [playState] = refIpc("TRACK_PLAYSTATE");
const [isHome] = refIpc("nav.same-origin", {
	defaultValue: true,
	mapper: ([sameOrigin]) => !!sameOrigin,
	rawArgs: true,
});
const [lastFM] = refIpc("LAST_FM_STATUS", {
	defaultValue: { connected: false, name: null, error: null },
	ignoreUndefined: true,
	getInitialValue: async () => {
		return await window.api.action(IPC_EVENT_NAMES.LAST_FM_STATUS);
	},
});
const stateHandle = ref<NodeJS.Timeout>();
const [lastFMState, setFmState] = refIpc<"start" | "change" | boolean | null>(IPC_EVENT_NAMES.LAST_FM_SUBMIT_STATE, {
	defaultValue: null,
	ignoreUndefined: true,
	onTrigger: (_fmstate, _prevfmstate) => {
		if (typeof _prevfmstate === "string" && typeof _fmstate === "boolean") {
			if (stateHandle.value) clearTimeout(stateHandle.value);
			stateHandle.value = setTimeout(() => {
				setFmState(null);
				logger.debug("clear fm submit state");
			}, 2000);
		}
	},
});
const lastFMLoading = ref(false);
const [discordEnabled, setDiscordEnabled] = refIpc("settingsProvider.change", {
	defaultValue: window.settings.get("discord.enabled"),
	mapper: ([key, value]) => {
		if (key === "discord.enabled") return value;
	},
	ignoreUndefined: true,
	getInitialValue: () => window.api.settingsProvider.get("discord.enabled", false),
	rawArgs: true,
});
const [isDev] = refIpc("settingsProvider.change", {
	defaultValue: window.settings.get("app.enableDev"),
	mapper: ([key, value]) => {
		if (key === "app.enableDev") return value;
	},
	ignoreUndefined: true,
	rawArgs: true,
});
onMounted(() => {
	window.ipcRenderer.invoke("req:discord.connected").then((x) => setDiscordConnected(!!x));
	window.api.action("lastfm.status").then((status) => {
		lastFM.value = status;
	});
});
const [updateChecking, setUpdateChecking] = refIpc<boolean>("APP_UPDATE_CHECKING");
const [updateInfo] = refIpc<UpdateInfo>("APP_UPDATE");
const [updateDownloaded] = refIpc<boolean>("APP_UPDATE_DOWNLOADED");

async function toggleSetting(key) {
	const setting = await window.api.settingsProvider.update(key, !window.settings.get(key));
	if (key === "discord.enabled") {
		setDiscordConnectionError(null);
		setDiscordEnabled(setting);
	}
}
function checkUpdate() {
	if (updateChecking.value) return;
	setUpdateChecking(true);
	window.api.action("app.checkUpdate").finally(() => {
		setUpdateChecking(false);
	});
}
function action(actionParam, ...params) {
	return window.api.action(actionParam, ...params);
}
function invoke(invokeParam, ...params) {
	return window.api.invoke(invokeParam, ...params);
}
function authorizeLastFM() {
	lastFMLoading.value = true;
	if (lastFM.value.connected) {
		action("lastfm.profile").finally(() => {
			lastFMLoading.value = false;
		});
		return;
	}
	invoke("lastfm.authorize").finally(() => {
		lastFMLoading.value = false;
	});
}
function onSettings() {
	window.api.openWindow("settingsWindow");
}
</script>
<style></style>
